name: Release and Publish - pkg.pr.new
on:
   pull_request:
   push:
      branches: main
      tags: ["!**"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
   test-release:
      runs-on: blacksmith-4vcpu-ubuntu-2204
      timeout-minutes: 15
      strategy:
         matrix:
            node-version: [20.x]

      steps:
         - name: Checkout repo
           uses: actions/checkout@v4

         - name: Setup pnpm
           uses: pnpm/action-setup@v4
           with:
              version: 9.15.4

         - name: Setup Node.js 20.x
           uses: useblacksmith/setup-node@v5
           with:
              node-version: ${{ matrix.node-version }}
              cache: pnpm

         - name: Install dependencies and build
           run: |
              pnpm install --frozen-lockfile
              pnpm build

         - name: Deploy and test release via pkg.pr.new
           run: pnpm release:test
